### PR TITLE
Extended test instructions

### PR DESCRIPTION
**Pull request by holgerbrandl**
Added more detailed instructions about how to setup and run the unit tests.

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Even if the redirection of the test-data to a different place than user.home works, it's still suboptimal since it also assumes the .m2 package index to be present there. Not sure if there is a more elegant solution to it.

**Comment by holgerbrandl** [comment]
I think the PR is not yet ready, because the way the caching of the test-data is directed is suboptimal, since it also makes maven to assume that the `.m2` is present in the same directory. I'll do more research to figure out a better solution

**Comment by holgerbrandl** [comment]
I removed the corresponding part and filed deeplearning4j/deeplearning4j#4962 instead.

**Comment by saudet** [comment]
Thanks for the contribution, but actually we should be releasing SNAPSHOT artifacts for dl4j-test-resources as well, so will not be needing instructions for the `git clone` part. @sshepel ?

**Comment by sshepel** [comment]
@holgerbrandl thanks for update, look good to me!
@saudet even though we will have snapshots for `dl4j-test-resources` I think it's nice to have explanation how to build test resources locally and how to use them...

**Comment by sshepel** [comment]
@crockpotveggies I'm ok to merge this... @saudet ?

**Pull request merged**
