### PR TITLE
[WIP] Updates to android.md 

### PR DESCRIPTION
**Pull request by jrmerwin**
[WIP] Updated the existing android.md documentation and included links to the new Android documents. This is a work in progress PR while I test and update dependency exclusions in the new android documents.

### CODE REVIEW

**Comment by crockpotveggies** [comment]
Ping me when you're ready to merge this 👍

**Comment by saudet** [comment]
@jrmerwin Thanks! Looks good. Now let's get this updated for 1.0.0-alpha :)

@crockpotveggies Can't merge, looks like "android-Prereqs and Configuration.md" got erased... ?

**Comment by crockpotveggies** [comment]
Looks like @chrisvnicholson changed the filename. Whitespace was removed from the file. @jrmerwin please do a `git pull` from the origin/master branch and this should merge the change into your branch. Then push the merge and we can finish this.

File is here now: https://github.com/deeplearning4j/deeplearning4j-docs/blob/gh-pages/android-prerequisites-configuration.md

**Comment by chrisvnicholson** [comment]
are we ready to publish this?

**Comment by merwijas** [comment]
It is showing no conflicts now so I believe we are ready to merge.

**Comment by crockpotveggies** [comment]
Thanks for the fixes @jrmerwin it's now live.

**Comment by saudet** [comment]
I see, it got renamed.

@jrmerwin You'll also need to update the links to that page in the other files!

**Comment by jrmerwin** [comment]
@saudet Oh you're right. I just finished updating them and checking all the links in all the documents. I'll send the pull request now.

**Pull request merged**
